fix: 修复 tag 支持 prerelease
cnpm/safe-publish-tag pull request #3
Opened 2020-10-12 09:33 UTC by chenpx976

2020-10-12 15:35 UTC, fengmk2 commented on package.json
> +    "version": "8, 10, 12",
6还不能去掉，否则得发 major 版本了。

2020-10-12 15:37 UTC, fengmk2 commented on test/index.test.js
> +    return safePublishTag('egg', '2.28.1-beta.0')
加一个非预期的错误 version 格式用例？

2020-10-12 15:37 UTC, fengmk2 requested changes
其他没问题了

2020-10-13 02:23 UTC, chenpx976 commented on package.json
> +    "version": "8, 10, 12",
好像是要发 major 了
https://github.com/cnpm/npminstall/blob/master/package.json#L87

2020-10-13 02:23 UTC, chenpx976 commented on package.json
> +    "version": "8, 10, 12",
CI 6 跑不过

https://travis-ci.org/github/cnpm/safe-publish-tag/jobs/735227324#L461

2020-10-13 02:25 UTC, chenpx976 commented on test/index.test.js
> +    return safePublishTag('egg', '2.28.1-beta.0')
加了一个限制 prerelease tag 是 alpha beta rc

2020-10-13 03:41 UTC, fengmk2 approved these changes

2020-10-13 03:42 UTC, fengmk2 commented
看来是 ci 工具已经放弃了 node 6 的支持

2020-10-13 03:42 UTC, merged